name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  name:
    description: 'Job Name'
    required: true
  url:
    description: 'Google Chat Webhook URL'
    required: true
  status:
    description: 'Job Status'
    required: true

branding:
  icon: 'bell'
  color: 'green'

runs:
  using: node20
  main: dist/index.js
