name: 'Google Chat Github Action'
description: 'Send a notification to Google Chat with the result of a GitHub Action'
author: 'JChrist'

# Define your inputs here.
inputs:
  name:
    description: 'Job Name'
    required: true
  url:
    description: 'Google Chat Webhook URL'
    required: true
  status:
    description: 'Job Status'
    required: true

branding:
  icon: 'bell'
  color: 'green'

runs:
  using: node20
  main: dist/index.js
